ectool_keyscan: add missing null terminator to kbd_plain_xlate
strchr relies on the source string to be null terminated. This fixes a
compiler warning when building outside of the chroot:

util/ectool_keyscan.c: In function ‘cmd_keyscan’:
util/ectool_keyscan.c:208:9: error: ‘strchr’ argument missing terminating nul [-Werror=stringop-overflow=]
  208 |   pos = strchr(kbd_plain_xlate, key);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

BUG=none
TEST=build only, warning is gone
BRANCH=none

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Change-Id: Iafb8249515ffa1a5f7e04a272e54a048eef9a57c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2606228
Reviewed-by: Keith Short <keithshort@chromium.org>
Reviewed-by: Simon Glass <sjg@chromium.org>
(cherry picked from commit 06a82155ef062adaccf3c2469c59ca850f5800c7)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2745223
Reviewed-by: Wai-Hong Tam <waihong@google.com>
Commit-Queue: Wai-Hong Tam <waihong@google.com>
Tested-by: Wai-Hong Tam <waihong@google.com>