common: add __test_only attribute
For functions which should only be used in test builds, this lets us
add __test_only to the prototype, causing an error if used outside of
tests.

Example error output:

test.c: In function ‘main’:
test.c:17:5: error: call to ‘foo’ declared with attribute error:
             This function should only be used by tests
    foo();
    ^~~~~

This will not cause errors if the usage is guarded by a disabled
IS_ENABLED (or any other form of optimized-away branch).

BUG=none
BRANCH=none
TEST=see above

Change-Id: I64115fd9e7940de9b10063a46548e8d00033d1d3
Signed-off-by: Jack Rosenthal <jrosenth@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/1872962
Reviewed-by: Daisuke Nojiri <dnojiri@chromium.org>
Reviewed-by: Raul E Rangel <rrangel@chromium.org>
(cherry picked from commit ab18c5ac746d3f332700fd13ed390359a3611a93)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/1928411
Reviewed-by: Eric Yilun Lin <yllin@chromium.org>
Commit-Queue: Eric Yilun Lin <yllin@chromium.org>
Tested-by: Eric Yilun Lin <yllin@chromium.org>