common: online_calibration: Fix compilation issue
- Fix compilation error: sizeof() of an input array
was not calculated properly.
- Fix calling convention: use sensor pointer instead of
sensor number
- Use common formula to calculate sensor number.

BUG=none
BRANCH=none
TEST=compile, unittest, load on eve with online calibration added.

(cherry picked from commit 512823a8aa87d4b6a83f88bab05fe586de6c14aa)

Change-Id: I06ff30eb5710cbe8f91c939b2ccc084c20a37847
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2486304
Reviewed-by: Yuval Peress <peress@chromium.org>
Signed-off-by: Gwendal Grignou <gwendal@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2705803