common/motion_sense: Avoid comparison between negative value and unsigned char
clang fails to compile due to the following:

common/motion_sense.c:1123:34: error: result of comparison of constant -1
with expression of type 'const uint8_t' (aka 'const unsigned char') is
always false [-Werror,-Wtautological-constant-out-of-range-compare]

(in->sensor_odr.sensor_num ==
~~~~~~~~~~~~~~~~~~~~~~~~~ ^

common/motion_sense.c:1454:27: error: result of comparison of constant -1
with expression of type 'const uint8_t' (aka 'const unsigned char') is
always false [-Werror,-Wtautological-constant-out-of-range-compare]

in->spoof.sensor_id == MOTION_SENSE_ACTIVITY_SENSOR_ID) {
~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

As indicated by the TEST line, the output is identical before and after
this change.

BRANCH=torgdor
BUG=b:172020503, b:243492849
TEST=./util/compare_build.sh -b all -j 90
     => MATCH

(cherry picked from commit 506dcb5e5b2aa1d4864a98972540ad95396ef372)
Signed-off-by: Tom Hughes <tomhughes@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3197753
Reviewed-by: Paul Fagerburg <pfagerburg@chromium.org>
Signed-off-by: Gwendal Grignou <gwendal@chromium.org>
Change-Id: Ieb55b385dfe9e07a8a7098ac3b456a0504215d94
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/3880540
Reviewed-by: Chao Gui <chaogui@google.com>
Commit-Queue: Bob Moragues <moragues@chromium.org>
Tested-by: Chao Gui <chaogui@google.com>
Reviewed-by: Bob Moragues <moragues@chromium.org>