ectool_keyscan: add missing null terminator to kbd_plain_xlate
strchr relies on the source string to be null terminated. This fixes a
compiler warning when building outside of the chroot:

util/ectool_keyscan.c: In function ‘cmd_keyscan’:
util/ectool_keyscan.c:208:9: error: ‘strchr’ argument missing terminating nul [-Werror=stringop-overflow=]
  208 |   pos = strchr(kbd_plain_xlate, key);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~

BUG=none
TEST=build only, warning is gone
BRANCH=none

Signed-off-by: Fabio Baltieri <fabiobaltieri@google.com>
Change-Id: Iafb8249515ffa1a5f7e04a272e54a048eef9a57c
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2606228
Reviewed-by: Keith Short <keithshort@chromium.org>
Reviewed-by: Simon Glass <sjg@chromium.org>
(cherry picked from commit 06a82155ef062adaccf3c2469c59ca850f5800c7)
Signed-off-by: Gwendal Grignou <gwendal@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2718319
Reviewed-by: Ting Shen <phoenixshen@chromium.org>
(cherry picked from commit 7e402ecaadded5744705f0bb6a50e63036054820)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/2729255
Tested-by: Mathew King <mathewk@chromium.org>
Tested-by: Martin Roth <martinroth@google.com>
Auto-Submit: Mathew King <mathewk@chromium.org>
Reviewed-by: Martin Roth <martinroth@google.com>
Commit-Queue: Martin Roth <martinroth@google.com>