tpmtest.py: update Makefile to correct build of ftdi_spi_tpm
make of ftdi_spi_tpm fails:
../../include/config.h:4878:25: fatal error: fuzz_config.h:
No such file or directory
 #include "fuzz_config.h"

It seems issue happened after moving fuzzing tests into a fuzz subfolder
in https://chromium-review.googlesource.com/1180179
Added include search path to correct issue.

BRANCH=none
BUG=none
TEST=in test/tpm_test/ make successfully builds ftdi_spi_tpm

Change-Id: I0c212ba7f84babd5db0c02d553345769de301d00
Signed-off-by: Vadim Sukhomlinov <sukhomlinov@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/1913325
Reviewed-by: Vadim Sukhomlinov <sukhomlinov@chromium.org>
Reviewed-by: Vadim Bendebury <vbendeb@chromium.org>
Commit-Queue: Vadim Bendebury <vbendeb@chromium.org>
Tested-by: Vadim Bendebury <vbendeb@chromium.org>
Auto-Submit: Vadim Sukhomlinov <sukhomlinov@chromium.org>
(cherry picked from commit 977c1267c00389de296cc7bdcf946badef4601aa)
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/ec/+/1918452
Reviewed-by: Tim Wawrzynczak <twawrzynczak@chromium.org>
Commit-Queue: Tim Wawrzynczak <twawrzynczak@chromium.org>
Tested-by: Tim Wawrzynczak <twawrzynczak@chromium.org>